// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/provider/provider.proto

package provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_proto_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *EntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArtistSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*ArtistResult        `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistSearchResponse) Reset() {
	*x = ArtistSearchResponse{}
	mi := &file_proto_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistSearchResponse) ProtoMessage() {}

func (x *ArtistSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistSearchResponse.ProtoReflect.Descriptor instead.
func (*ArtistSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ArtistSearchResponse) GetArtists() []*ArtistResult {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *ArtistSearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ArtistResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AlbumCount    int32                  `protobuf:"varint,4,opt,name=album_count,json=albumCount,proto3" json:"album_count,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistResult) Reset() {
	*x = ArtistResult{}
	mi := &file_proto_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistResult) ProtoMessage() {}

func (x *ArtistResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistResult.ProtoReflect.Descriptor instead.
func (*ArtistResult) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ArtistResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ArtistResult) GetAlbumCount() int32 {
	if x != nil {
		return x.AlbumCount
	}
	return 0
}

func (x *ArtistResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ArtistResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ArtistDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistDetail) Reset() {
	*x = ArtistDetail{}
	mi := &file_proto_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistDetail) ProtoMessage() {}

func (x *ArtistDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistDetail.ProtoReflect.Descriptor instead.
func (*ArtistDetail) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ArtistDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistDetail) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ArtistDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AlbumList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*AlbumSummary        `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumList) Reset() {
	*x = AlbumList{}
	mi := &file_proto_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumList) ProtoMessage() {}

func (x *AlbumList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumList.ProtoReflect.Descriptor instead.
func (*AlbumList) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *AlbumList) GetAlbums() []*AlbumSummary {
	if x != nil {
		return x.Albums
	}
	return nil
}

type AlbumSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	RecordType    string                 `protobuf:"bytes,5,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Rank          int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumSummary) Reset() {
	*x = AlbumSummary{}
	mi := &file_proto_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumSummary) ProtoMessage() {}

func (x *AlbumSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumSummary.ProtoReflect.Descriptor instead.
func (*AlbumSummary) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{8}
}

func (x *AlbumSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlbumSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlbumSummary) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *AlbumSummary) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AlbumSummary) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *AlbumSummary) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AlbumSummary) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AlbumDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	ArtistName    string                 `protobuf:"bytes,5,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Tracks        []*TrackInfo           `protobuf:"bytes,6,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumDetail) Reset() {
	*x = AlbumDetail{}
	mi := &file_proto_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumDetail) ProtoMessage() {}

func (x *AlbumDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumDetail.ProtoReflect.Descriptor instead.
func (*AlbumDetail) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{9}
}

func (x *AlbumDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlbumDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlbumDetail) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *AlbumDetail) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AlbumDetail) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *AlbumDetail) GetTracks() []*TrackInfo {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *AlbumDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TrackNumber   int32                  `protobuf:"varint,3,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	DiscNumber    int32                  `protobuf:"varint,4,opt,name=disc_number,json=discNumber,proto3" json:"disc_number,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Rank          int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_proto_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_proto_provider_provider_proto_rawDescGZIP(), []int{10}
}

func (x *TrackInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackInfo) GetTrackNumber() int32 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

func (x *TrackInfo) GetDiscNumber() int32 {
	if x != nil {
		return x.DiscNumber
	}
	return 0
}

func (x *TrackInfo) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TrackInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *TrackInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_provider_provider_proto protoreflect.FileDescriptor

const file_proto_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/provider/provider.proto\x12\x11crate.provider.v1\"\r\n" +
	"\vInfoRequest\"_\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x1f\n" +
	"\rEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x14ArtistSearchResponse\x129\n" +
	"\aartists\x18\x01 \x03(\v2\x1f.crate.provider.v1.ArtistResultR\aartists\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8c\x02\n" +
	"\fArtistResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\valbum_count\x18\x04 \x01(\x05R\n" +
	"albumCount\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12I\n" +
	"\bmetadata\x18\x06 \x03(\v2-.crate.provider.v1.ArtistResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\fArtistDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.crate.provider.v1.ArtistDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\tAlbumList\x127\n" +
	"\x06albums\x18\x01 \x03(\v2\x1f.crate.provider.v1.AlbumSummaryR\x06albums\"\xa2\x02\n" +
	"\fAlbumSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1f\n" +
	"\vrecord_type\x18\x05 \x01(\tR\n" +
	"recordType\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\x12I\n" +
	"\bmetadata\x18\a \x03(\v2-.crate.provider.v1.AlbumSummary.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\vAlbumDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1f\n" +
	"\vartist_name\x18\x05 \x01(\tR\n" +
	"artistName\x124\n" +
	"\x06tracks\x18\x06 \x03(\v2\x1c.crate.provider.v1.TrackInfoR\x06tracks\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.crate.provider.v1.AlbumDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\tTrackInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\ftrack_number\x18\x03 \x01(\x05R\vtrackNumber\x12\x1f\n" +
	"\vdisc_number\x18\x04 \x01(\x05R\n" +
	"discNumber\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.crate.provider.v1.TrackInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa5\x03\n" +
	"\rMusicProvider\x12G\n" +
	"\x04Info\x12\x1e.crate.provider.v1.InfoRequest\x1a\x1f.crate.provider.v1.InfoResponse\x12Z\n" +
	"\rSearchArtists\x12 .crate.provider.v1.SearchRequest\x1a'.crate.provider.v1.ArtistSearchResponse\x12N\n" +
	"\tGetArtist\x12 .crate.provider.v1.EntityRequest\x1a\x1f.crate.provider.v1.ArtistDetail\x12Q\n" +
	"\x0fGetArtistAlbums\x12 .crate.provider.v1.EntityRequest\x1a\x1c.crate.provider.v1.AlbumList\x12L\n" +
	"\bGetAlbum\x12 .crate.provider.v1.EntityRequest\x1a\x1e.crate.provider.v1.AlbumDetailB6Z4github.com/TheOutdoorProgrammer/crate/proto/providerb\x06proto3"

var (
	file_proto_provider_provider_proto_rawDescOnce sync.Once
	file_proto_provider_provider_proto_rawDescData []byte
)

func file_proto_provider_provider_proto_rawDescGZIP() []byte {
	file_proto_provider_provider_proto_rawDescOnce.Do(func() {
		file_proto_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_provider_provider_proto_rawDesc), len(file_proto_provider_provider_proto_rawDesc)))
	})
	return file_proto_provider_provider_proto_rawDescData
}

var file_proto_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_provider_provider_proto_goTypes = []any{
	(*InfoRequest)(nil),          // 0: crate.provider.v1.InfoRequest
	(*InfoResponse)(nil),         // 1: crate.provider.v1.InfoResponse
	(*SearchRequest)(nil),        // 2: crate.provider.v1.SearchRequest
	(*EntityRequest)(nil),        // 3: crate.provider.v1.EntityRequest
	(*ArtistSearchResponse)(nil), // 4: crate.provider.v1.ArtistSearchResponse
	(*ArtistResult)(nil),         // 5: crate.provider.v1.ArtistResult
	(*ArtistDetail)(nil),         // 6: crate.provider.v1.ArtistDetail
	(*AlbumList)(nil),            // 7: crate.provider.v1.AlbumList
	(*AlbumSummary)(nil),         // 8: crate.provider.v1.AlbumSummary
	(*AlbumDetail)(nil),          // 9: crate.provider.v1.AlbumDetail
	(*TrackInfo)(nil),            // 10: crate.provider.v1.TrackInfo
	nil,                          // 11: crate.provider.v1.ArtistResult.MetadataEntry
	nil,                          // 12: crate.provider.v1.ArtistDetail.MetadataEntry
	nil,                          // 13: crate.provider.v1.AlbumSummary.MetadataEntry
	nil,                          // 14: crate.provider.v1.AlbumDetail.MetadataEntry
	nil,                          // 15: crate.provider.v1.TrackInfo.MetadataEntry
}
var file_proto_provider_provider_proto_depIdxs = []int32{
	5,  // 0: crate.provider.v1.ArtistSearchResponse.artists:type_name -> crate.provider.v1.ArtistResult
	11, // 1: crate.provider.v1.ArtistResult.metadata:type_name -> crate.provider.v1.ArtistResult.MetadataEntry
	12, // 2: crate.provider.v1.ArtistDetail.metadata:type_name -> crate.provider.v1.ArtistDetail.MetadataEntry
	8,  // 3: crate.provider.v1.AlbumList.albums:type_name -> crate.provider.v1.AlbumSummary
	13, // 4: crate.provider.v1.AlbumSummary.metadata:type_name -> crate.provider.v1.AlbumSummary.MetadataEntry
	10, // 5: crate.provider.v1.AlbumDetail.tracks:type_name -> crate.provider.v1.TrackInfo
	14, // 6: crate.provider.v1.AlbumDetail.metadata:type_name -> crate.provider.v1.AlbumDetail.MetadataEntry
	15, // 7: crate.provider.v1.TrackInfo.metadata:type_name -> crate.provider.v1.TrackInfo.MetadataEntry
	0,  // 8: crate.provider.v1.MusicProvider.Info:input_type -> crate.provider.v1.InfoRequest
	2,  // 9: crate.provider.v1.MusicProvider.SearchArtists:input_type -> crate.provider.v1.SearchRequest
	3,  // 10: crate.provider.v1.MusicProvider.GetArtist:input_type -> crate.provider.v1.EntityRequest
	3,  // 11: crate.provider.v1.MusicProvider.GetArtistAlbums:input_type -> crate.provider.v1.EntityRequest
	3,  // 12: crate.provider.v1.MusicProvider.GetAlbum:input_type -> crate.provider.v1.EntityRequest
	1,  // 13: crate.provider.v1.MusicProvider.Info:output_type -> crate.provider.v1.InfoResponse
	4,  // 14: crate.provider.v1.MusicProvider.SearchArtists:output_type -> crate.provider.v1.ArtistSearchResponse
	6,  // 15: crate.provider.v1.MusicProvider.GetArtist:output_type -> crate.provider.v1.ArtistDetail
	7,  // 16: crate.provider.v1.MusicProvider.GetArtistAlbums:output_type -> crate.provider.v1.AlbumList
	9,  // 17: crate.provider.v1.MusicProvider.GetAlbum:output_type -> crate.provider.v1.AlbumDetail
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_provider_provider_proto_init() }
func file_proto_provider_provider_proto_init() {
	if File_proto_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_provider_provider_proto_rawDesc), len(file_proto_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_provider_provider_proto_goTypes,
		DependencyIndexes: file_proto_provider_provider_proto_depIdxs,
		MessageInfos:      file_proto_provider_provider_proto_msgTypes,
	}.Build()
	File_proto_provider_provider_proto = out.File
	file_proto_provider_provider_proto_goTypes = nil
	file_proto_provider_provider_proto_depIdxs = nil
}
