// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/provider/provider.proto

package provider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MusicProvider_Info_FullMethodName            = "/crate.provider.v1.MusicProvider/Info"
	MusicProvider_SearchArtists_FullMethodName   = "/crate.provider.v1.MusicProvider/SearchArtists"
	MusicProvider_GetArtist_FullMethodName       = "/crate.provider.v1.MusicProvider/GetArtist"
	MusicProvider_GetArtistAlbums_FullMethodName = "/crate.provider.v1.MusicProvider/GetArtistAlbums"
	MusicProvider_GetAlbum_FullMethodName        = "/crate.provider.v1.MusicProvider/GetAlbum"
)

// MusicProviderClient is the client API for MusicProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MusicProviderClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	SearchArtists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ArtistSearchResponse, error)
	GetArtist(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*ArtistDetail, error)
	GetArtistAlbums(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AlbumList, error)
	GetAlbum(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AlbumDetail, error)
}

type musicProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicProviderClient(cc grpc.ClientConnInterface) MusicProviderClient {
	return &musicProviderClient{cc}
}

func (c *musicProviderClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, MusicProvider_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderClient) SearchArtists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ArtistSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistSearchResponse)
	err := c.cc.Invoke(ctx, MusicProvider_SearchArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderClient) GetArtist(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*ArtistDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistDetail)
	err := c.cc.Invoke(ctx, MusicProvider_GetArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderClient) GetArtistAlbums(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AlbumList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumList)
	err := c.cc.Invoke(ctx, MusicProvider_GetArtistAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderClient) GetAlbum(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AlbumDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumDetail)
	err := c.cc.Invoke(ctx, MusicProvider_GetAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicProviderServer is the server API for MusicProvider service.
// All implementations must embed UnimplementedMusicProviderServer
// for forward compatibility.
type MusicProviderServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	SearchArtists(context.Context, *SearchRequest) (*ArtistSearchResponse, error)
	GetArtist(context.Context, *EntityRequest) (*ArtistDetail, error)
	GetArtistAlbums(context.Context, *EntityRequest) (*AlbumList, error)
	GetAlbum(context.Context, *EntityRequest) (*AlbumDetail, error)
	mustEmbedUnimplementedMusicProviderServer()
}

// UnimplementedMusicProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMusicProviderServer struct{}

func (UnimplementedMusicProviderServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedMusicProviderServer) SearchArtists(context.Context, *SearchRequest) (*ArtistSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtists not implemented")
}
func (UnimplementedMusicProviderServer) GetArtist(context.Context, *EntityRequest) (*ArtistDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtist not implemented")
}
func (UnimplementedMusicProviderServer) GetArtistAlbums(context.Context, *EntityRequest) (*AlbumList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistAlbums not implemented")
}
func (UnimplementedMusicProviderServer) GetAlbum(context.Context, *EntityRequest) (*AlbumDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbum not implemented")
}
func (UnimplementedMusicProviderServer) mustEmbedUnimplementedMusicProviderServer() {}
func (UnimplementedMusicProviderServer) testEmbeddedByValue()                       {}

// UnsafeMusicProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MusicProviderServer will
// result in compilation errors.
type UnsafeMusicProviderServer interface {
	mustEmbedUnimplementedMusicProviderServer()
}

func RegisterMusicProviderServer(s grpc.ServiceRegistrar, srv MusicProviderServer) {
	// If the following call panics, it indicates UnimplementedMusicProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MusicProvider_ServiceDesc, srv)
}

func _MusicProvider_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProvider_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProvider_SearchArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServer).SearchArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProvider_SearchArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServer).SearchArtists(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProvider_GetArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServer).GetArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProvider_GetArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServer).GetArtist(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProvider_GetArtistAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServer).GetArtistAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProvider_GetArtistAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServer).GetArtistAlbums(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProvider_GetAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServer).GetAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProvider_GetAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServer).GetAlbum(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MusicProvider_ServiceDesc is the grpc.ServiceDesc for MusicProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MusicProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crate.provider.v1.MusicProvider",
	HandlerType: (*MusicProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _MusicProvider_Info_Handler,
		},
		{
			MethodName: "SearchArtists",
			Handler:    _MusicProvider_SearchArtists_Handler,
		},
		{
			MethodName: "GetArtist",
			Handler:    _MusicProvider_GetArtist_Handler,
		},
		{
			MethodName: "GetArtistAlbums",
			Handler:    _MusicProvider_GetArtistAlbums_Handler,
		},
		{
			MethodName: "GetAlbum",
			Handler:    _MusicProvider_GetAlbum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/provider/provider.proto",
}
